-- 003 · Bronze operational data: orders, delivery events, route plans and route history
--
-- Event tables carry the three metadata columns: source, event_time and ingested_at.
-- Rows that arrive in batch files also keep raw_object_key, the key of the file in the RustFS
-- bronze bucket, so every row traces back to the payload it was parsed from.
-- Event tables have no foreign keys to reference data: a raw record must never be rejected
-- because a reference table was loaded late. dbt relationship tests check them in silver.

CREATE TABLE bronze.orders (
    order_id                  text PRIMARY KEY,
    service_date              date NOT NULL,
    service_level             text NOT NULL CHECK (service_level IN ('same_day', 'next_day')),
    priority                  text NOT NULL DEFAULT 'normal' CHECK (priority IN ('high', 'normal', 'low')),
    customer_type             text NOT NULL CHECK (customer_type IN ('B2C', 'B2B')),
    shipper_name              text NOT NULL,
    origin_address            text NOT NULL,
    recipient_name            text,
    destination_address       text NOT NULL,
    destination_postcode      text,
    destination_municipality  text NOT NULL,
    destination_lat           double precision NOT NULL CHECK (destination_lat BETWEEN 40.5 AND 42.9),
    destination_lon           double precision NOT NULL CHECK (destination_lon BETWEEN 0.1 AND 3.4),
    destination_zone_id       text NOT NULL,
    address_ref               text,
    parcels                   smallint NOT NULL DEFAULT 1 CHECK (parcels > 0),
    parcel_size               text NOT NULL CHECK (parcel_size IN ('small', 'medium', 'large')),
    weight_kg                 numeric(6, 2) CHECK (weight_kg > 0),
    window_start              timestamptz,
    window_end                timestamptz,
    notes                     text,
    source                    text NOT NULL REFERENCES ops.data_sources,
    event_time                timestamptz NOT NULL,
    ingested_at               timestamptz NOT NULL DEFAULT now(),
    raw_object_key            text,
    CHECK (window_end > window_start)
);
COMMENT ON TABLE bronze.orders IS '{"owner": "operations", "schema_version": 1}';
COMMENT ON COLUMN bronze.orders.event_time IS 'When the shipper registered the order.';
COMMENT ON COLUMN bronze.orders.origin_address IS 'Where the parcel comes from: the shipper''s warehouse or the partner network that hands it over.';
COMMENT ON COLUMN bronze.orders.recipient_name IS 'Fictional, AI-generated. Personal data in a real company: bronze is not readable by Grafana.';
COMMENT ON COLUMN bronze.orders.address_ref IS 'Identifier of the destination in the Open Data BCN address table (taula-direle).';
COMMENT ON COLUMN bronze.orders.notes IS 'Free-text delivery instructions written by the recipient. Unstructured.';
CREATE INDEX ON bronze.orders (service_date, destination_zone_id);

CREATE TABLE bronze.delivery_events (
    event_id        uuid PRIMARY KEY,
    order_id        text NOT NULL,
    route_id        text,
    stop_sequence   smallint CHECK (stop_sequence > 0),
    vehicle_id      text,
    driver_id       text,
    status          text NOT NULL CHECK (status IN ('loaded', 'arrived', 'delivered', 'failed', 'returned')),
    failure_reason  text CHECK (failure_reason IN
                        ('recipient_absent', 'address_not_found', 'refused', 'access_restricted', 'damaged', 'other')),
    lat             double precision CHECK (lat BETWEEN 40.5 AND 42.9),
    lon             double precision CHECK (lon BETWEEN 0.1 AND 3.4),
    pod_object_key  text,
    source          text NOT NULL REFERENCES ops.data_sources,
    event_time      timestamptz NOT NULL,
    ingested_at     timestamptz NOT NULL DEFAULT now(),
    CHECK (status <> 'failed' OR failure_reason IS NOT NULL),
    CHECK (pod_object_key IS NULL OR status = 'delivered')
);
COMMENT ON TABLE bronze.delivery_events IS '{"owner": "operations", "schema_version": 1}';
COMMENT ON COLUMN bronze.delivery_events.event_id IS 'Generated by the handheld, so a replayed Kafka message is written once.';
COMMENT ON COLUMN bronze.delivery_events.event_time IS 'When the driver scanned the parcel.';
COMMENT ON COLUMN bronze.delivery_events.pod_object_key IS 'Key of the proof-of-delivery photo in the RustFS bronze bucket (pod/...).';
CREATE INDEX ON bronze.delivery_events (route_id, event_time);
CREATE INDEX ON bronze.delivery_events (order_id, event_time);

CREATE TABLE bronze.route_plans (
    route_id               text NOT NULL,
    plan_version           smallint NOT NULL CHECK (plan_version >= 0),
    planner                text NOT NULL CHECK (planner IN ('baseline', 'optimizer')),
    replan_reason          text NOT NULL CHECK (replan_reason IN
                               ('initial', 'traffic', 'delay', 'failed_delivery', 'weather', 'manual')),
    service_date           date NOT NULL,
    wave                   text NOT NULL CHECK (wave IN ('morning', 'afternoon')),
    zone_id                text NOT NULL,
    vehicle_id             text NOT NULL,
    driver_id              text,
    stops                  smallint NOT NULL CHECK (stops >= 0),
    planned_departure      timestamptz NOT NULL,
    planned_completion     timestamptz NOT NULL,
    planned_distance_km    numeric(6, 2) CHECK (planned_distance_km >= 0),
    solver_status          text,
    source                 text NOT NULL REFERENCES ops.data_sources,
    event_time             timestamptz NOT NULL,
    ingested_at            timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (route_id, plan_version),
    CHECK (planned_completion > planned_departure),
    CHECK ((plan_version = 0) = (planner = 'baseline'))
);
COMMENT ON TABLE bronze.route_plans IS '{"owner": "operations", "schema_version": 1}';
COMMENT ON COLUMN bronze.route_plans.plan_version IS '0 is the baseline plan made before departure; 1 and up are re-plans by the optimizer.';
COMMENT ON COLUMN bronze.route_plans.event_time IS 'When the plan was computed.';
CREATE INDEX ON bronze.route_plans (service_date, zone_id);

CREATE TABLE bronze.route_plan_stops (
    route_id          text NOT NULL,
    plan_version      smallint NOT NULL,
    stop_sequence     smallint NOT NULL CHECK (stop_sequence > 0),
    order_id          text NOT NULL,
    planned_arrival   timestamptz NOT NULL,
    leg_distance_km   numeric(6, 2) CHECK (leg_distance_km >= 0),
    leg_duration_s    integer CHECK (leg_duration_s >= 0),
    source            text NOT NULL REFERENCES ops.data_sources,
    event_time        timestamptz NOT NULL,
    ingested_at       timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (route_id, plan_version, stop_sequence),
    UNIQUE (route_id, plan_version, order_id),
    FOREIGN KEY (route_id, plan_version) REFERENCES bronze.route_plans ON DELETE CASCADE
);
COMMENT ON TABLE bronze.route_plan_stops IS '{"owner": "operations", "schema_version": 1}';
COMMENT ON COLUMN bronze.route_plan_stops.event_time IS 'When the plan was computed, as on the plan header.';

CREATE TABLE bronze.route_history (
    route_id              text PRIMARY KEY,
    service_date          date NOT NULL,
    wave                  text NOT NULL CHECK (wave IN ('morning', 'afternoon')),
    zone_id               text NOT NULL,
    vehicle_id            text NOT NULL,
    driver_id             text,
    completed_at          timestamptz NOT NULL,
    planned_duration_min  numeric(5, 1) CHECK (planned_duration_min > 0),
    stops_planned         smallint NOT NULL CHECK (stops_planned >= 0),
    stops_delivered       smallint NOT NULL CHECK (stops_delivered >= 0),
    stops_failed          smallint NOT NULL CHECK (stops_failed >= 0),
    distance_km           numeric(6, 2) CHECK (distance_km >= 0),
    source                text NOT NULL REFERENCES ops.data_sources,
    event_time            timestamptz NOT NULL,
    ingested_at           timestamptz NOT NULL DEFAULT now(),
    raw_object_key        text,
    CHECK (completed_at > event_time),
    CHECK (stops_delivered + stops_failed <= stops_planned)
);
COMMENT ON TABLE bronze.route_history IS '{"owner": "operations", "schema_version": 1}';
COMMENT ON COLUMN bronze.route_history.event_time IS 'When the van left the hub geofence (departed_at of the KPI).';
COMMENT ON COLUMN bronze.route_history.completed_at IS 'Last delivered or failed scan of the route (completed_at of the KPI).';
CREATE INDEX ON bronze.route_history (service_date, zone_id);
