apiVersion: 1

datasources:
  - name: TimescaleDB
    uid: timescaledb
    type: grafana-postgresql-datasource
    access: proxy
    url: timescaledb:5432
    user: grafana_reader
    isDefault: true
    editable: false
    jsonData:
      database: ${POSTGRES_DB}
      sslmode: disable
      postgresVersion: 1700
      timescaledb: true
    secureJsonData:
      password: ${GRAFANA_DB_PASSWORD}
